#ifndef __LIBIOPCTASKHTTP_H__
#define __LIBIOPCTASKHTTP_H__

//#define HTTPD_FLAGS     MHD_USE_EPOLL_INTERNALLY_LINUX_ONLY | MHD_USE_EPOLL_LINUX_ONLY | MHD_USE_DEBUG
#define HTTPD_FLAGS     MHD_USE_SELECT_INTERNALLY | MHD_USE_DEBUG
#define HTTPD_PORT      80
#define HTTPD_IP	"192.168.200.254"

#endif
